Update launch method using async
mtsgi/kit pull request #73
Opened 2019-11-16 05:23 UTC by taichanNE30

## Add
### Variables
- Boolean Sysyem.launchLock

### Functions
- System.waitLaunchUnlock
- System.ajaxWait

## Change
### Functions
- launch
- appData

## Remarks
変数名とかメソッド名、追加位置などで不備があれば変更します。
一応、正常にlaunchが動作することは確認済みです。

2019-11-22 05:49 UTC, mtsgi requested changes
`System.launch` にも非同期機構が欲しいです

2019-11-22 05:59 UTC, taichanNE30 commented
> `System.launch` にも非同期機構が欲しいです
Done

2019-11-23 02:02 UTC, mtsgi approved these changes
Looks Good To Meです

2019-11-25 10:23 UTC, taichanNE30 commented
僕mergeできないのでいいタイミングでやってください

2019-11-28 04:57 UTC, merged